// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnuswrmzgwobwlpifqok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudXN3cm16Z3dvYndscGlmcW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODE5NjIsImV4cCI6MjA3MjM1Nzk2Mn0.6z3F94iH5Ihno45LLbYXbyX7wyEnd7l6uO2wF2sAPqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});